### ISSUE TITLE
希望支持最大下单量功能，提升资金利用率

### ISSUE THREAD

**Issue by dos2004** [Loopring/vnpy#3]
目前通过config配置每次的买卖单下单量，如果想收益最大化则配置的下单量为当前可以买卖的最大值。
如果挂单被成交一部分，则无法继续下单，需要重新修改下单量，重新编译docker file再跑。
整个过程不够智能，无法做到无人值守。

希望支持最大下单量功能，提升资金利用率。
举个例子：
那usdc–usdt来说，有1000usdt，当前挂买单价格0.9998，那么可以下的最大买单量就是1000/0.9998.
5分钟后挂单被成交了100usdt，那么可以下的最大买单量应该是900/0.9998。

对于稳定币挖矿，增加该功能后可以提升资金利用率。

**Comment by yueawang** [comment]
Done by #4
